---
abstract: 'utility functions for Sledge'
author:
  - 'Tokuhiro Matsuno  C<< <tokuhiro __at__ mobilefactory.jp> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sledge-Utils
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Filter::Util::Call: 0
  String::CamelCase: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
